"""Day 9 unit coverage for :mod:`aegis.data.ticker_reference`.

Seven tests against the locally-generated ``ticker_metadata.parquet`` and
the checked-in ``ticker_aliases.csv``:

- 6 from the locked Week 2 plan ([docs/plans/week2.md:93-99]):
  delisted-have-delisted-date, active-have-null-delisted-date,
  is_active_on boundary, canonicalize rename, canonicalize identity,
  delisted-excluded-from-universe-post-inactive (the survivorship
  acceptance per reviewer's note).

- 1 added by the proposal-compliance audit (§4.1 σ-algebra
  measurability regression guard, mirroring Day 8's pattern).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd
import pytest

from aegis.data.ticker_reference import (
    ALIAS_COLUMNS,
    METADATA_COLUMNS,
    canonicalize_ticker,
    is_active_on,
    load_ticker_aliases,
    load_ticker_metadata,
)

# tests/unit/test_ticker_reference.py -> repo root is two parents up.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_METADATA_PATH = _REPO_ROOT / "data" / "reference" / "ticker_metadata.parquet"
_ALIASES_PATH = _REPO_ROOT / "data" / "reference" / "ticker_aliases.csv"


# Shared fixtures. The Parquet is gitignored (regenerated by the Polygon
# scraper) so we skip these tests in environments where it hasn't been
# generated yet — same pattern as @pytest.mark.polygon on the live tests.
_SKIP_NO_PARQUET = pytest.mark.skipif(
    not _METADATA_PATH.exists(),
    reason="ticker_metadata.parquet not generated; run scripts/fetch_polygon_ticker_reference.py",
)


@pytest.fixture(scope="module")
def metadata() -> pd.DataFrame:
    if not _METADATA_PATH.exists():
        pytest.skip("ticker_metadata.parquet not generated")
    return load_ticker_metadata(_METADATA_PATH)


@pytest.fixture(scope="module")
def aliases() -> pd.DataFrame:
    return load_ticker_aliases(_ALIASES_PATH)


# --- Test 1: known-delisted tickers carry a delisted_date ---------------------


@_SKIP_NO_PARQUET
def test_known_delisted_tickers_have_delisted_date(metadata: pd.DataFrame) -> None:
    """TWTR / MON / CELG were all S&P 500 members with clean acquisitions."""
    for ticker in ("TWTR", "MON", "CELG"):
        rows = metadata[metadata["ticker"] == ticker]
        assert not rows.empty, f"{ticker} missing from ticker_metadata.parquet"
        assert rows["delisted_date"].notna().all(), (
            f"{ticker} should have a delisted_date but it's null"
        )


# --- Test 2: known-active tickers have null delisted_date ---------------------


@_SKIP_NO_PARQUET
def test_known_active_tickers_have_null_delisted_date(metadata: pd.DataFrame) -> None:
    for ticker in ("AAPL", "MSFT", "GOOGL", "JNJ"):
        rows = metadata[metadata["ticker"] == ticker]
        assert not rows.empty, f"{ticker} missing from ticker_metadata.parquet"
        assert rows["delisted_date"].isna().all(), (
            f"{ticker} is active but has a non-null delisted_date"
        )


# --- Test 3: boundary semantics on the exact delisting date -------------------


@_SKIP_NO_PARQUET
def test_is_active_on_boundary_day(metadata: pd.DataFrame) -> None:
    """§4.1: removal date is the *first* day no longer active.

    The day before the delisted date should be active; the delisted date
    itself should not.
    """
    twtr_rows = metadata[metadata["ticker"] == "TWTR"]
    assert not twtr_rows.empty
    twtr_delisted = twtr_rows["delisted_date"].iloc[0]
    assert pd.notna(twtr_delisted)

    day_before = (twtr_delisted - pd.Timedelta(days=1)).date()
    day_of = twtr_delisted.date()

    assert is_active_on("TWTR", day_before, metadata) is True, (
        f"TWTR should be active on {day_before} (day before delist)"
    )
    assert is_active_on("TWTR", day_of, metadata) is False, (
        f"TWTR should NOT be active on {day_of} (delist date itself)"
    )


# --- Test 4: rename resolution ------------------------------------------------


def test_canonicalize_ticker_resolves_rename(aliases: pd.DataFrame) -> None:
    """FB→META and the WLP→ANTM→ELV chain."""
    # FB rename was 2022-06-09. Pre-rename, symbol is FB; post, META.
    assert canonicalize_ticker("FB", date(2018, 6, 15), aliases) == "FB"
    assert canonicalize_ticker("FB", date(2023, 1, 1), aliases) == "META"

    # WLP→ANTM (2014-12-03) → ELV (2022-06-28)
    assert canonicalize_ticker("WLP", date(2010, 1, 1), aliases) == "WLP"
    assert canonicalize_ticker("WLP", date(2018, 6, 15), aliases) == "ANTM"
    assert canonicalize_ticker("WLP", date(2024, 1, 1), aliases) == "ELV"

    # And starting from an intermediate symbol still resolves correctly.
    assert canonicalize_ticker("ANTM", date(2018, 6, 15), aliases) == "ANTM"
    assert canonicalize_ticker("ANTM", date(2024, 1, 1), aliases) == "ELV"


# --- Test 5: identity case ----------------------------------------------------


def test_canonicalize_ticker_identity(aliases: pd.DataFrame) -> None:
    """Tickers with no alias rows are returned unchanged on any date."""
    for d in (date(2010, 1, 1), date(2020, 6, 15), date(2026, 4, 27)):
        assert canonicalize_ticker("AAPL", d, aliases) == "AAPL"
        assert canonicalize_ticker("MSFT", d, aliases) == "MSFT"


# --- Test 6: survivorship-tracker acceptance (per reviewer's note) ------------


@_SKIP_NO_PARQUET
def test_known_delisted_ticker_excluded_from_universe_post_inactive_date(
    metadata: pd.DataFrame,
) -> None:
    """For TWTR and MON, is_active_on flips correctly across their boundaries."""
    # TWTR — Musk acquisition; Polygon delisted_utc is 2022-10-31.
    assert is_active_on("TWTR", date(2022, 6, 1), metadata) is True
    assert is_active_on("TWTR", date(2023, 1, 1), metadata) is False

    # MON — Bayer acquisition; delisted 2018-06-07 (Polygon may report a
    # nearby date). Pre-2018 should be active; post-2019 should not.
    assert is_active_on("MON", date(2017, 1, 2), metadata) is True
    assert is_active_on("MON", date(2019, 1, 2), metadata) is False


# --- Test 7: §4.1 σ-algebra measurability regression guard --------------------


@_SKIP_NO_PARQUET
def test_is_active_on_is_filtration_measurable(metadata: pd.DataFrame) -> None:
    """Spec §4.1 regression: per-ticker activity at t uses only F_t-measurable rows.

    Mirrors the Day 8 measurability test for ``active_on``. For each
    ticker active on ``t``, restricting the metadata frame to rows with
    ``list_date <= t`` (or null list_date) must yield the same answer.
    """
    t = date(2018, 6, 15)
    ts = pd.Timestamp(t)

    sample = ["AAPL", "MSFT", "JNJ", "MON", "TWTR", "TSLA"]
    full_answers = {ticker: is_active_on(ticker, t, metadata) for ticker in sample}

    # F_t-restricted view: drop rows whose list_date is in the future.
    restricted = metadata[metadata["list_date"].isna() | (metadata["list_date"] <= ts)]
    restricted_answers = {ticker: is_active_on(ticker, t, restricted) for ticker in sample}

    assert full_answers == restricted_answers, (
        f"is_active_on is not filtration-measurable at {t}: "
        f"full={full_answers} vs restricted={restricted_answers}"
    )


# --- Bonus: schema sanity (catches column-renames during refactors) -----------


@_SKIP_NO_PARQUET
def test_ticker_metadata_schema(metadata: pd.DataFrame) -> None:
    assert tuple(metadata.columns) == METADATA_COLUMNS
    assert metadata["ticker"].notna().all()
    assert metadata["ticker"].is_unique


def test_ticker_aliases_schema(aliases: pd.DataFrame) -> None:
    assert tuple(aliases.columns) == ALIAS_COLUMNS
    assert len(aliases) >= 10, "expected at least 10 high-impact aliases"
    bad = (
        aliases["effective_from"].notna()
        & aliases["effective_to"].notna()
        & (aliases["effective_to"] < aliases["effective_from"])
    )
    assert not bad.any()
